name: Build website

on: push
#on:
#  push:
#    branches:
#      - main

env:
  OUTPUT_DIR: pandoc-output

jobs:
  build_static_website:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/core:2.14
      options: --entrypoint=sh
    steps:

      - name: Install dependencies
        run: apk add make git

      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Convert via pandoc
        run: make

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ${{ env.OUTPUT_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
