name: Build website

on: [push, workflow_dispatch]

env:
  OUTPUT_DIR: pandoc-output

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: docker://pandoc/core:3.6-ubuntu
      options: --entrypoint=sh
    steps:

      - name: Install dependencies
        run: apt update && apt install -y git make

      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Convert via pandoc
        run: make

      - name: Copy custom domain name configuration
        run: |
          (test -f CNAME && cp CNAME ${{ env.OUTPUT_DIR }}) || echo "CNAME not there yet"

      - name: Upload as artifact for GH pages
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.OUTPUT_DIR }}

  deploy:
    needs: build
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
